// <auto-generated />
//------------------------------------------------------------------------------
// This code is auto-generated.
// Do not attempt to edit this file by hand, you could hurt yourself!
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using Type_Statement = System.String;
using Type_Token = Buffalo.Core.Test.Token;

namespace Buffalo.Generated.ShiftReduceConflict
{
	internal enum TokenType
	{
		ElseKeyword = 2,
		EOF = 1,
		IfKeyword = 3,
		Other = 0,
	}

	internal abstract class AutoParser
	{
		// [Statistics]
		// Reductions          : 4
		// Terminals           : 4 (4 columns)
		// NonTerminals        : 2 (2 columns)
		// States              : 8
		//   Short Circuited   : 4
		//   With Goto Entries : 3
		//   With SR Conflicts : 1
		//   Other             : 0
		// Transition Table    : 24/48(50.00%)
		//   Primary Offsets   : 8
		//   Goto Offsets      : 3
		//   Actions           : 13
		// Memory Footprint    : 48 bytes
		// Assembly Footprint  : 48 bytes (100.00%)
		protected AutoParser()
		{
			_transitionTable = GetTransitionTable();
		}

		public Type_Statement Parse(IEnumerable<Type_Token> tokens)
		{
			return (Type_Statement)Parse(tokens, 0).value;
		}

		State Parse(IEnumerable<Type_Token> tokens, int initialState)
		{
			List<State> stack = new List<State>();

			{
				State init = new State();
				init.state = initialState;
				stack.Add(init);
			}

			int state = initialState;

			using (IEnumerator<Type_Token> enumerator = tokens.GetEnumerator())
			{
				bool haveToken = enumerator.MoveNext();

				while (haveToken)
				{
					Type_Token token = enumerator.Current;
					TokenType type = GetTokenType(token);

					{
						int offset = _transitionTable[state];
						int action = offset <= 5 ? offset : _transitionTable[offset + (int)type];

						if (action > 5)
						{
							State newState = new State();
							newState.state = state = action - 5;
							newState.value = token;

							stack.Add(newState);
							haveToken = enumerator.MoveNext();
						}
						else if (action > 1)
						{
							int reductionId = action - 2;
							state = Reduce(reductionId, stack);
						}
						else if (action == 0 || type != TokenType.EOF)
						{
							UnexpectedToken(token);
							throw new InvalidOperationException("unexpected token: " + type);
						}
						else
						{
							return stack[1];
						}
					}
				}
			}

			throw new InvalidOperationException("ran out of tokens, somehow");
		}

		int Reduce(int reductionId, List<State> stack)
		{
			State newState = new State();
			int gotoIndex;

			switch (reductionId)
			{
				case 1: // <Statement> -> <If>
					newState.value = Reduce_Statement_1((Type_Statement)stack[stack.Count - 1].value);
					gotoIndex = 0;
					stack.RemoveAt(stack.Count - 1);
					break;

				case 0: // <Statement> -> Other
					newState.value = null;
					gotoIndex = 0;
					stack.RemoveAt(stack.Count - 1);
					break;

				case 2: // <If> -> IfKeyword <Statement>
					newState.value = Reduce_If_1((Type_Token)stack[stack.Count - 2].value, (Type_Statement)stack[stack.Count - 1].value);
					gotoIndex = 1;
					stack.RemoveRange(stack.Count - 2, 2);
					break;

				case 3: // <If> -> IfKeyword <Statement> ElseKeyword <Statement>
					newState.value = Reduce_If_2((Type_Token)stack[stack.Count - 4].value, (Type_Statement)stack[stack.Count - 3].value, (Type_Token)stack[stack.Count - 2].value, (Type_Statement)stack[stack.Count - 1].value);
					gotoIndex = 1;
					stack.RemoveRange(stack.Count - 4, 4);
					break;

				default: throw new InvalidOperationException("unknown reduction");
			}

			int state = stack[stack.Count - 1].state;
			newState.state = _transitionTable[_transitionTable[state + 8] + gotoIndex];

			stack.Add(newState);

			return newState.state;
		}

		protected virtual void UnexpectedToken(Type_Token terminal)
		{
		}

		static ushort[] Extract(string resourceName)
		{
			using (System.IO.Stream stream = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName))
			{
				int len = (int)stream.Length;
				ushort[] result = new ushort[len >> 1];
				byte[] buffer = new byte[Math.Min(stream.Length, 512)];
				int offset = 0;
				int read;

				do
				{
					read = stream.Read(buffer, 0, buffer.Length);
					Buffer.BlockCopy(buffer, 0, result, offset, read);
					offset += read;
				}
				while (offset < len && read > 0);

				return result;
			}
		}

		protected abstract TokenType GetTokenType(Type_Token terminal);

		protected abstract Type_Statement Reduce_Statement_1(Type_Statement ifSeg);
		protected abstract Type_Statement Reduce_If_1(Type_Token ifKeywordSeg, Type_Statement statementSeg);
		protected abstract Type_Statement Reduce_If_2(Type_Token ifKeywordSeg, Type_Statement statementSeg1, Type_Token elseKeywordSeg, Type_Statement statementSeg2);

		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		readonly ushort[] _transitionTable;

		struct State
		{
			public int state;
			public object value;
		}

		static ushort[] GetTransitionTable()
		{
			return Extract("Buffalo.Core.Test.Parser.Generation.Gramour.AutoParserShiftReduceConflict.table");
		}
	}
}
