// <auto-generated />
//------------------------------------------------------------------------------
// This code is auto-generated.
// Do not attempt to edit this file by hand, you could hurt yourself!
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using Type_Segment = System.String;
using Type_Token = Buffalo.Core.Test.Token;

namespace Buffalo.Generated.GotoOnlyStates
{
	internal enum TokenType
	{
		A = 1,
		B = 2,
		EOF = 0,
	}

	internal abstract class AutoParser
	{
		// [Statistics]
		// Reductions          : 3
		// Terminals           : 3 (3 columns)
		// NonTerminals        : 1 (1 column)
		// States              : 4
		//   Short Circuited   : 2
		//   With Goto Entries : 1
		//   With SR Conflicts : 2
		//   Other             : 0
		// Transition Table    : 11/16(68.75%)
		//   Primary Offsets   : 4
		//   Goto Offsets      : 1
		//   Actions           : 6
		// Memory Footprint    : 22 bytes
		// Assembly Footprint  : 22 bytes (100.00%)
		protected AutoParser()
		{
			_transitionTable = GetTransitionTable();
		}

		public Type_Segment Parse(IEnumerable<Type_Token> tokens)
		{
			return (Type_Segment)Parse(tokens, 0).value;
		}

		State Parse(IEnumerable<Type_Token> tokens, int initialState)
		{
			List<State> stack = new List<State>();

			{
				State init = new State();
				init.state = initialState;
				stack.Add(init);
			}

			int state = initialState;

			using (IEnumerator<Type_Token> enumerator = tokens.GetEnumerator())
			{
				bool haveToken = enumerator.MoveNext();

				while (haveToken)
				{
					Type_Token token = enumerator.Current;
					TokenType type = GetTokenType(token);

					{
						int offset = _transitionTable[state];
						int action = offset <= 4 ? offset : _transitionTable[offset + (int)type];

						if (action > 4)
						{
							State newState = new State();
							newState.state = state = action - 4;
							newState.value = token;

							stack.Add(newState);
							haveToken = enumerator.MoveNext();
						}
						else if (action > 1)
						{
							int reductionId = action - 2;
							state = Reduce(reductionId, stack);
						}
						else if (action == 0 || type != TokenType.EOF)
						{
							UnexpectedToken(token);
							throw new InvalidOperationException("unexpected token: " + type);
						}
						else
						{
							return stack[1];
						}
					}
				}
			}

			throw new InvalidOperationException("ran out of tokens, somehow");
		}

		int Reduce(int reductionId, List<State> stack)
		{
			State newState = new State();
			int gotoIndex;

			switch (reductionId)
			{
				case 1: // <L> -> <L> A
					newState.value = Reduce_L_1((Type_Segment)stack[stack.Count - 2].value, (Type_Token)stack[stack.Count - 1].value);
					gotoIndex = 0;
					stack.RemoveRange(stack.Count - 2, 2);
					break;

				case 2: // <L> -> <L> A B
					newState.value = Reduce_L_2((Type_Segment)stack[stack.Count - 3].value, (Type_Token)stack[stack.Count - 2].value, (Type_Token)stack[stack.Count - 1].value);
					gotoIndex = 0;
					stack.RemoveRange(stack.Count - 3, 3);
					break;

				case 0: // <L> ->
					newState.value = Reduce_L_3();
					gotoIndex = 0;
					break;

				default: throw new InvalidOperationException("unknown reduction");
			}

			int state = stack[stack.Count - 1].state;
			newState.state = _transitionTable[_transitionTable[state + 4] + gotoIndex];

			stack.Add(newState);

			return newState.state;
		}

		protected virtual void UnexpectedToken(Type_Token terminal)
		{
		}

		static ushort[] Extract(string resourceName)
		{
			using (System.IO.Stream stream = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName))
			{
				int len = (int)stream.Length;
				ushort[] result = new ushort[len >> 1];
				byte[] buffer = new byte[Math.Min(stream.Length, 512)];
				int offset = 0;
				int read;

				do
				{
					read = stream.Read(buffer, 0, buffer.Length);
					Buffer.BlockCopy(buffer, 0, result, offset, read);
					offset += read;
				}
				while (offset < len && read > 0);

				return result;
			}
		}

		protected abstract TokenType GetTokenType(Type_Token terminal);

		protected abstract Type_Segment Reduce_L_1(Type_Segment lSeg, Type_Token aSeg);
		protected abstract Type_Segment Reduce_L_2(Type_Segment lSeg, Type_Token aSeg, Type_Token bSeg);
		protected abstract Type_Segment Reduce_L_3();

		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		readonly ushort[] _transitionTable;

		struct State
		{
			public int state;
			public object value;
		}

		static ushort[] GetTransitionTable()
		{
			return Extract("Buffalo.Core.Test.Parser.Generation.Gramour.AutoParserGotoOnlyStates.table");
		}
	}
}
