// <auto-generated />
//------------------------------------------------------------------------------
// This code is auto-generated.
// Do not attempt to edit this file by hand, you could hurt yourself!
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using Type_Token = Buffalo.Core.Test.Token;
using Type_Value = System.String;

namespace Buffalo.Generated.OptionalSegments
{
	internal enum TokenType
	{
		A = 2,
		B = 0,
		EOF = 1,
	}

	internal abstract class AutoParser
	{
		// [Statistics]
		// Reductions          : 4
		// Terminals           : 3 (3 columns)
		// NonTerminals        : 3 (1 column)
		// States              : 6
		//   Short Circuited   : 3
		//   With Goto Entries : 3
		//   With SR Conflicts : 2
		//   Other             : 0
		// Transition Table    : 20/24(83.33%)
		//   Primary Offsets   : 6
		//   Goto Offsets      : 3
		//   Actions           : 11
		// Memory Footprint    : 40 bytes
		// Assembly Footprint  : 40 bytes (100.00%)
		protected AutoParser()
		{
			_transitionTable = GetTransitionTable();
		}

		public Type_Value Parse(IEnumerable<Type_Token> tokens)
		{
			return (Type_Value)Parse(tokens, 0).value;
		}

		State Parse(IEnumerable<Type_Token> tokens, int initialState)
		{
			List<State> stack = new List<State>();

			{
				State init = new State();
				init.state = initialState;
				stack.Add(init);
			}

			int state = initialState;

			using (IEnumerator<Type_Token> enumerator = tokens.GetEnumerator())
			{
				bool haveToken = enumerator.MoveNext();

				while (haveToken)
				{
					Type_Token token = enumerator.Current;
					TokenType type = GetTokenType(token);

					{
						int offset = _transitionTable[state];
						int action = offset <= 5 ? offset : _transitionTable[offset + (int)type];

						if (action > 5)
						{
							State newState = new State();
							newState.state = state = action - 5;
							newState.value = token;

							stack.Add(newState);
							haveToken = enumerator.MoveNext();
						}
						else if (action > 1)
						{
							int reductionId = action - 2;
							state = Reduce(reductionId, stack);
						}
						else if (action == 0 || type != TokenType.EOF)
						{
							UnexpectedToken(token);
							throw new InvalidOperationException("unexpected token: " + type);
						}
						else
						{
							return stack[1];
						}
					}
				}
			}

			throw new InvalidOperationException("ran out of tokens, somehow");
		}

		int Reduce(int reductionId, List<State> stack)
		{
			State newState = new State();
			int gotoIndex;

			switch (reductionId)
			{
				case 2: // <Document> -> A <A>?
					newState.value = Reduce_Document_1((Type_Token)stack[stack.Count - 2].value, (Type_Token)stack[stack.Count - 1].value);
					gotoIndex = 0;
					stack.RemoveRange(stack.Count - 2, 2);
					break;

				case 3: // <Document> -> B B?
					newState.value = Reduce_Document_2((Type_Token)stack[stack.Count - 2].value, (Type_Token)stack[stack.Count - 1].value);
					gotoIndex = 0;
					stack.RemoveRange(stack.Count - 2, 2);
					break;

				case 0: // <A>? ->
					newState.value = null;
					gotoIndex = 0;
					break;

				case 1: // B? ->
					newState.value = null;
					gotoIndex = 0;
					break;

				default: throw new InvalidOperationException("unknown reduction");
			}

			int state = stack[stack.Count - 1].state;
			newState.state = _transitionTable[_transitionTable[state + 6] + gotoIndex];

			stack.Add(newState);

			return newState.state;
		}

		protected virtual void UnexpectedToken(Type_Token terminal)
		{
		}

		static ushort[] Extract(string resourceName)
		{
			using (System.IO.Stream stream = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName))
			{
				int len = (int)stream.Length;
				ushort[] result = new ushort[len >> 1];
				byte[] buffer = new byte[Math.Min(stream.Length, 512)];
				int offset = 0;
				int read;

				do
				{
					read = stream.Read(buffer, 0, buffer.Length);
					Buffer.BlockCopy(buffer, 0, result, offset, read);
					offset += read;
				}
				while (offset < len && read > 0);

				return result;
			}
		}

		protected abstract TokenType GetTokenType(Type_Token terminal);

		protected abstract Type_Value Reduce_Document_1(Type_Token aSeg1, Type_Token aSeg2);
		protected abstract Type_Value Reduce_Document_2(Type_Token bSeg1, Type_Token bSeg2);

		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		readonly ushort[] _transitionTable;

		struct State
		{
			public int state;
			public object value;
		}

		static ushort[] GetTransitionTable()
		{
			return Extract("Buffalo.Core.Test.Parser.Generation.Gramour.AutoParserOptionalSegments.table");
		}
	}
}
